"""update stock field

Revision ID: 6e4da0017c63
Revises: 119bcee90ff6
Create Date: 2024-11-27 21:48:22.478849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4da0017c63'
down_revision: Union[str, None] = '119bcee90ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('book', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('book', 'quantity')
    # ### end Alembic commands ###
